UPDATE GROUP
SET CACHET_HABITUEL = CACHET_HABITUEL + (0,035*CACHET_HABITUEL);

UPDATE CONTRAT
SET CACHET_PREVU = CACHET_PREVU - (0,10*CACHET_PREVU)
WHERE HEURE_DEBUT_PRESTATION = 18 OR 19
AND HEURE_FIN_PRESTATION = <22;
